### ISSUE TITLE
Error upon import

### ISSUE THREAD

**Issue by aiq-andrew** [tanium/pytan3#3]
I get an import error when attempting to use this library in 2.7.15. I believe it may be because of circular dependency, removing line 14 in auth_store/__init__.py appeared to resolve this issue.

The Code:
`    
from pytan3.http_client import HttpClient
from pytan3.api_clients import Rest
from pytan3.auth_methods import RestCredentials

tanium_http = HttpClient("https://[redacted].com")
tanium_auth = RestCredentials(tanium_http, '[redacted]', '[redacted]')
tanium_api = Rest(tanium_http, tanium_auth)
`

The Error:
`
Uncaught Exception and no log output at 'ERROR' level for Logger(name='pytan3', level='DEBUG', disabled=False, handlers: NO OUTPUT HANDLERS)
Traceback (most recent call last):
  File "/[redacted]/main.py", line 22, in <module>
    from pytan3.http_client import HttpClient
  File "/[redacted]/.venv/lib/python2.7/site-packages/pytan3/__init__.py", line 12, in <module>
    from . import auth_methods
  File "/[redacted]/.venv/lib/python2.7/site-packages/pytan3/auth_methods/__init__.py", line 17, in <module>
    from .. import auth_store
  File "/[redacted]/.venv/lib/python2.7/site-packages/pytan3/auth_store/__init__.py", line 14, in <module>
    from .. import auth_methods
ImportError: cannot import name auth_methods`

**Comment by lifehackjim** [comment]
I no longer work at Tanium, but feel free to email me at jim@lifehack.com and I can assist.

**Comment by 99jasonjohnson** [comment]
Andrew, if you are an existing Tanium customer please feel free to contact support@tanium.com as well.  Alternatively, we encourage review of our REST API now available.  Thanks!
